### ISSUE TITLE
Start of the code review process

### ISSUE THREAD

**Issue by longnd** [foreverLoveWisdom/google_search_extractor#14]
Hello Tien 👋 
Thank you for your effort on the code submission. I am Long, engineering lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by longnd** [comment]
I have completed the first round of reviews. Please provide your feedback on all open issues.

**Comment by foreverLoveWisdom** [comment]
Hi Long 👋,

Thank you for taking the time to review my code submission. It's great you're open to hearing more about my decisions and approach.

I appreciate the opportunity to ask questions and share their thoughts during the review process.🤔

It's great to hear that you'll be following proper git flow for addressing any issues during the review as well.😊

I understand you hope to complete the code review process within 2-3 days, and I will be responsive during that time and will let you know immediately if they need additional time. 🕒

Thanks again for your time and effort in reviewing my code. I'm sure the process will be enjoyable and productive. 🚀

**Comment by foreverLoveWisdom** [comment]
> I have completed the first round of reviews. Please provide your feedback on all open issues.

Thank you for your time and effort. 🙏

I am reviewing the issues right now and will let you know my thoughts and approaches for each issue.

**Comment by longnd** [comment]
I have reviewed the open pull requests. It is time to wrap up the code review process.

Thank you for your efforts so far. Our team will provide feedback to you by email.

**Comment by foreverLoveWisdom** [comment]
Thanks, @longnd, again for your time and effort. I understand that you have your daily task need to be taken care of, and I appreciate it. :bow:
