### ISSUE TITLE
[Chore] Incomplete setup instruction

### ISSUE THREAD

**Issue by longnd** [foreverLoveWisdom/google_search_extractor#15]
Issue
---
While the README file has the [Installation](https://github.com/foreverLoveWisdom/google_search_extractor/tree/develop#%EF%B8%8F-installation) instruction to setup the app on local, it is incomplete. There is the step to build the assets, e.g. using `yarn build`.
The app uses [forman](https://github.com/ddollar/foreman) to run several process defined in `procfile.dev`, it should be ideal to have it documented in the README to ease the setup process.
Ideally, the application can be dockerized to make the setup easier. I'm also wondering if you are you familiar with Docker and did you dockerized an application before?

Expected
--
The local setup process is straightforward and shouldn't take time to figure out the missing piece.

**Comment by foreverLoveWisdom** [comment]
> ## Issue
> While the README file has the [Installation](https://github.com/foreverLoveWisdom/google_search_extractor/tree/develop#%EF%B8%8F-installation) instruction to setup the app on local, it is incomplete. There is the step to build the assets, e.g. using `yarn build`. The app uses [forman](https://github.com/ddollar/foreman) to run several process defined in `procfile.dev`, it should be ideal to have it documented in the README to ease the setup process. Ideally, the application can be dockerized to make the setup easier. I'm also wondering if you are you familiar with Docker and did you dockerized an application before?
> 
> ## Expected
> The local setup process is straightforward and shouldn't take time to figure out the missing piece.

* I got it. I will update the instruction on the README to make it more transparent and easier for other developers.
* I did dockerize my application in the past(a Rails side project with PostgreSQL, Redis, and Docker Compose...), but since my previous companies didn't use Docker much(just a standard setup), so I stopped using it. If the company or organization requires me to use Docker, I am happy to re-use it.

**Comment by foreverLoveWisdom** [comment]
- :wave: Hi @longnd, based on your suggestion, I have improved the documentation to make it clearer for other developers to set up their local development and created the [PR](https://github.com/foreverLoveWisdom/google_search_extractor/pull/23) :heavy_check_mark:
- :bow: Please help to verify it and let me know if you have any further questions or suggestions :smiley:

**Comment by longnd** [comment]
hi @foreverLoveWisdom. 
There is one thing I forget to mention - I assume you also use `config/database.yml` to set the DB config for local environment, right? (even though it was not mentioned in the setup instruction)

Thank you for spending effort on the fix.
